#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as the shebang line:
#
#           #!/usr/bin/env ksh
#           #!/usr/bin/env bash
#           #!/usr/bin/env zsh
#
#       This must be the very first line of the script (ignoring the "#!" line if it
#       exists) and the shebang line must start with "#!/usr/bin/env".  We recommend
#       using bash because it's the most widely supported POSIX-compliant shell.
#
#       For example: to use bash, replace "#!/bin/sh" with "#!/usr/bin/env bash"
#
#   (2) On the Pi (yocto) machine, the default shell is a non-POSIX-compliant busybox
#       ash.  You can fix that by changing the shebang line to "#!/bin/env bash" or
#       to use "bash" as the shebang, you may need to change the shebang line to
#       "#!/bin/bash".
#
#   (3) If you know the script will be run under a POSIX-compliant shell, the
#       shebang can be "#!/bin/sh".  This is the default.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$(cd "${APP_HOME:-./}" > /dev/null && pwd -P) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in
      max*)
        # In POSIX sh, ulimit -n is undefined.  Because it's unknown, it's treated as "unlimited"
        # (i.e. no limit) in the shell's parser.
        #
        # In a future version of POSIX, ulimit -n may be defined as a special builtin.
        #
        # In bash, "unlimited" is the default for ulimit -n.
        #
        # We try to detect this so we can set the hard limit (which may be "unlimited" or a number) to
        # a high number if possible.  If we can't detect it, we'll set the soft limit to a soft
        # high default value (65536) hoping that it works on the platform.  This will work on
        # most POSIX-compliant shells (it's the default value on many platforms).  However, on
        # csh and tcsh, this will fail as the default value is not 65536, and we can't run ulimit
        # -n to set it because 'ulimit' is not a builtin in csh.
        MAX_FD_DEFAULT=65536
        # Try to get the hard limit.  If we get a non-zero exit code, assume "unlimited"
        # (i.e. we can't query the hard limit).
        hard_limit=$(ulimit -Hn 2>/dev/null) || hard_limit=
        if [ -n "$hard_limit" ] && [ "$hard_limit" != "unlimited" ]; then
            # We have a hard limit that is a number.  Compare it to our default.  If our default is
            # greater than the hard limit, set the hard limit to our default.
            if [ $MAX_FD_DEFAULT -gt $hard_limit ] ; then
                MAX_FD=$hard_limit
            else
                MAX_FD=$MAX_FD_DEFAULT
            fi
        else
            # Either the hard limit is "unlimited" (meaning no limit) or we could not query it.
            # We'll set the soft limit (which we may not be able to set if we can't query the hard
            # limit) to a high number (which is "unlimited" from the perspective of most apps).
            MAX_FD=$MAX_FD_DEFAULT
        fi
        ;;
    esac

    # If we are on a POSIX platform, we need to set the soft limit, not the hard limit.
    # The 'ulimit' builtin has two options:
    #   -S - soft limit
    #   -H - hard limit
    # macOS's ulimit (it's actually a separate tool, not a builtin) has a -H option, but it's
    # not for setting the hard limit - it's for a different purpose.  See
    # https://kevinlawler.com/ulimit
    # for the details.  We'll just try both -S and -H and if neither is recognized, we'll try
    # without any option (which may set the hard limit, but that's fine).
    for flag in -S -H ''; do
        if ulimit $flag -n > /dev/null 2>&1 ; then
            ulimit $flag -n $MAX_FD
            break
        fi
    done
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if dedicated module module-path is used)
#   * --module (only if an explicit module is used)
#   * All other arguments (likely -D and -X arguments are directly after the classpath)

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$(cygpath --path --ignore --mixed "$arg")
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position it started in, but
        # possibly modified.
        #
        # NB: a `for` loop resets its `in` part (args) so we can't use `for`
        # directly; instead we need to capture the current state of the args
        # list so we can loop through them.
        args=$*                   # capture the current state of the args list
        set --                    # then reset $@ to empty
        # shellcheck disable=SC2254  # the $arg may include spaces, but it's ok as it's quoted.
        for arg in "$@" ; do      # then loop over the current args again (the ones we just captured)
            set -- "$@" "$arg"    # push each arg back into the resulting args list
        done
    done
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in double quotes as well to account for characters like
#     space, \, ", etc.  (e.g. 'a=b' -> 'a=b' and 'a="b"' -> 'a="b"')
#   * For Cygwin or MSYS, we need to ensure that we evaluate the arguments as a single
#     string before we pass it to java, but also need to ensure that the arguments
#     can be safely split on the first space when building the classpath.

# This function is used to join arguments into a single string for Cygwin/MSYS.
join_by() {
    local IFS="$1"; shift; echo "$*"
}

# For Cygwin or MSYS, convert the args to a single string to ensure that the
# native java parser can properly interpret things like 'a b' and 'a="b"'.
# In other environments, we just pass all the arguments as an array to Java.
if "$cygwin" || "$msys" ; then
    DEFAULT_JVM_OPTS=$(join_by : "${DEFAULT_JVM_OPTS:-}")
    JAVA_OPTS=$(join_by : "${JAVA_OPTS:-}")
    GRADLE_OPTS=$(join_by : "${GRADLE_OPTS:-}")

    args=()
    for arg in "$@"; do
        # Escape any backslashes that happen to be part of the argument before
        # converting them so they don't get unescaped and cause problems later
        arg=${arg//\\/\\\\}

        # Add quotes around arguments that have spaces or other special characters in them
        case $arg in
          *\ * ) arg="\"$arg\"" ;;
        esac
        args=("${args[@]}" "$arg")
    done

    # Now that we have the arguments as a string in $args for cygwin/msys, add
    # the runtime arguments and then wrap the whole thing in double quotes
    # (because we need to pass this as a single argument to the java command),
    # but also escape any double quotes so they don't get interpreted by the
    # java command.
    runtimeArgs=()
    # shellcheck disable=SC2086  # we want the splitting of the default JVM opts for cygwin/msys
    for arg in $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS; do
        arg=${arg//\\/\\\\}
        arg=${arg//\"/\\\"}
        runtimeArgs=("${runtimeArgs[@]}" "$arg")
    done
    runtimeArgs=("${runtimeArgs[@]}" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$@")
    arg_string=$(printf "%s\n" "${runtimeArgs[@]}" | join_by " ")
    arg_string="\"$arg_string\""
    # Now we can run the java command with the $arg_string
    eval "$JAVACMD $arg_string"
else
    # Now on POSIX
    # Older java versions (9 and earlier) have a bug that they do not handle
    # empty elements in the classpath correctly (i.e. they will treat `:""` and
    # `:` as the same thing).  To work around that we ensure that the classpath
    # does not contain empty elements.
    # Note that this approach may break if the classpath contains quoted
    # elements, which may be the case.  Since the classpath is set via the
    # CLASSPATH environment variable, we cannot guarantee it does not contain
    # quoted elements.  If this becomes a problem, we need to change the approach
    # (probably to use -cp and don't use the CLASSPATH variable).
    if [ -n "$CLASSPATH" ] ; then
        # Split the classpath into individual components (it's usually separated by :)
        IFS=: read -r -a classpath_elements <<< "$CLASSPATH"
        # Remove empty elements from the classpath
        new_classpath_elements=()
        for element in "${classpath_elements[@]}"; do
            if [ -n "$element" ]; then
                new_classpath_elements+=("$element")
            fi
        done
        CLASSPATH=$(IFS=:; echo "${new_classpath_elements[*]}")
    fi

    # Build the command line arguments array, using the "set --" trick to pass
    # them to java.
    set -- \
        -Dorg.gradle.appname="$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

    # For sh compatibility (POSIX), we need to ensure that the arguments that
    # we plan to pass are properly formatted as an array.  We'll set the
    # arguments as the current arguments (via set --) but we need to escape any
    # embedded double quotes.
    escaped_args=()
    for arg in "$@"; do
        # Escape any embedded double quotes
        arg=${arg//\"/\\\"}
        escaped_args+=("$arg")
    done

    # In the sh shell (and POSIX compliant ones), we can set the arguments
    # with the command substitution `set -- $(printf "%s\n" "${args[@]}")`.
    # However, we can't easily escape the arguments with printf, so we just
    # pass them through as an array.  The JVM should do the right thing
    # (hopefully).  If it doesn't, then we need to re-implement the cygwin/msys
    # path above for plain POSIX sh.
    eval set -- "${escaped_args[@]}"

    "$JAVACMD" "${args_array[@]}"
fi
